### ISSUE TITLE
Please dont save oauth token into memory under production

### ISSUE THREAD

**Issue by JoeShi** [wenwei1202/passport-wechat-public#2]
一直报这个warning.

请问怎么解决呢？

**Comment by vcwen** [comment]
这个warning是来自wechat-Oauth, 是因为没有保存token到数据库，没有提供saveToken 和getToken, 默认的是保存在内存，这样在cluster模式下，会导致重复向微信请求accesstoken, 但是对OAuth的access token的请求现在微信是没有限制的，所以问题不大，我之前直接忽略了。 我这两天修改下，提供这样可以自己加saveToken和getToken的callback函数

**Comment by JoeShi** [comment]
太感谢了，坐等 fix.

**Comment by vcwen** [comment]
@JoeShi  已经fix了，options里可以直接给getToken和saveToken函数来保存和获取accesstoken了,中间修改了个snsapi_base情况下返回的profile的openId的key改成了openid，统一了下名字，如果你有用到的话注意下，版本现在是0.2.0
